
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - DATABASE_URL=postgres://admin:admin@postgres:5432/postgres
      - PORT=3000
      - JWT_SECRET=secret_key

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge